-- CreateEnum
CREATE TYPE "COMMITTEE_TYPE" AS ENUM ('PENGURUS_INTI', 'BADAN_PENGURUS_HARIAN');

-- CreateEnum
CREATE TYPE "PENGURUS_INTI_TYPE" AS ENUM ('PROJECT_OFFICER', 'VICE_PROJECT_OFFICER_INTERNAL', 'VICE_PROJECT_OFFICER_EXTERNAL', 'SEKRETARIS_UMUM', 'CONTROLLER', 'TRASURER', 'KOORDINATOR_BIDANG_ACARA', 'KOORDINATOR_SARANA_DAN_PRASANARANA', 'KOORDINATOR_OPERASIONAL', 'KOORDINATOR_MATERI_DAN_MENTOR', 'KOORDINATOR_KREATIF', 'KOORDINATOR_RELASI');

-- CreateEnum
CREATE TYPE "BADAN_PENGURUS_HARIAN_TYPE" AS ENUM ('PROJECT', 'SPONSORSHIP', 'KESEKRETARIATAN', 'PSDM', 'ACARA_PUNCAK', 'EKSPLORASI', 'TRANSPORTASI_DAN_KONSUMSI', 'PERIZINAN', 'LOGISTIK', 'KEAMANAN', 'MEDIS', 'MEDIA_INFORMASI', 'KELEMBAGAAN', 'MATERI', 'MENTOR', 'MEDIA_PARTNER', 'IT_DAN_BROADCAST', 'DEKORASI_DAN_WARDROBE', 'VISUAL_DESIGN_DAN_DOKUMENTASI');

-- CreateEnum
CREATE TYPE "ENTRANCE_METHOD" AS ENUM ('SNBP', 'SNBT', 'MANDIRI', 'BEASISWA');

-- CreateEnum
CREATE TYPE "SPONSOR_PACKAGE" AS ENUM ('SILVER', 'GOLD', 'PLATINUM');

-- CreateTable
CREATE TABLE "Event" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    "start_date" TIMESTAMP(3) NOT NULL,
    "end_date" TIMESTAMP(3) NOT NULL,
    "name" STRING NOT NULL,
    "description" STRING,
    "location" STRING NOT NULL,

    CONSTRAINT "Event_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Committee" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "faculty" STRING NOT NULL,
    "major" STRING NOT NULL,
    "entrance_year" INT4 NOT NULL,
    "committee_type" "COMMITTEE_TYPE" NOT NULL,
    "pengurus_inti_type" "PENGURUS_INTI_TYPE",
    "bph_type" "BADAN_PENGURUS_HARIAN_TYPE",

    CONSTRAINT "Committee_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Group" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "number" INT4 NOT NULL,
    "mentor_id" INT4 NOT NULL,

    CONSTRAINT "Group_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Mentee" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "faculty" STRING NOT NULL,
    "major" STRING NOT NULL,
    "entrance_year" INT4 NOT NULL,
    "entrance_method" "ENTRANCE_METHOD" NOT NULL,
    "group_number" INT4 NOT NULL,

    CONSTRAINT "Mentee_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Sponsor" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,
    "package" "SPONSOR_PACKAGE" NOT NULL,

    CONSTRAINT "Sponsor_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Speaker" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL,

    CONSTRAINT "Speaker_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "_EventToSpeaker" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateTable
CREATE TABLE "_EventToSponsor" (
    "A" INT4 NOT NULL,
    "B" INT4 NOT NULL
);

-- CreateIndex
CREATE UNIQUE INDEX "Group_number_key" ON "Group"("number");

-- CreateIndex
CREATE UNIQUE INDEX "Group_mentor_id_key" ON "Group"("mentor_id");

-- CreateIndex
CREATE UNIQUE INDEX "Sponsor_name_package_key" ON "Sponsor"("name", "package");

-- CreateIndex
CREATE UNIQUE INDEX "_EventToSpeaker_AB_unique" ON "_EventToSpeaker"("A", "B");

-- CreateIndex
CREATE INDEX "_EventToSpeaker_B_index" ON "_EventToSpeaker"("B");

-- CreateIndex
CREATE UNIQUE INDEX "_EventToSponsor_AB_unique" ON "_EventToSponsor"("A", "B");

-- CreateIndex
CREATE INDEX "_EventToSponsor_B_index" ON "_EventToSponsor"("B");

-- AddForeignKey
ALTER TABLE "Group" ADD CONSTRAINT "Group_mentor_id_fkey" FOREIGN KEY ("mentor_id") REFERENCES "Committee"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Mentee" ADD CONSTRAINT "Mentee_group_number_fkey" FOREIGN KEY ("group_number") REFERENCES "Group"("number") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EventToSpeaker" ADD CONSTRAINT "_EventToSpeaker_A_fkey" FOREIGN KEY ("A") REFERENCES "Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EventToSpeaker" ADD CONSTRAINT "_EventToSpeaker_B_fkey" FOREIGN KEY ("B") REFERENCES "Speaker"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EventToSponsor" ADD CONSTRAINT "_EventToSponsor_A_fkey" FOREIGN KEY ("A") REFERENCES "Event"("id") ON DELETE CASCADE ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "_EventToSponsor" ADD CONSTRAINT "_EventToSponsor_B_fkey" FOREIGN KEY ("B") REFERENCES "Sponsor"("id") ON DELETE CASCADE ON UPDATE CASCADE;
